### ISSUE TITLE
Build in Debian 10 fails

### ISSUE THREAD

**Issue by fernandodrf** [tari-project/tari#1999]
Hi there, I am trying to build from source in a Debian 10 system, so far I followed the instructions and installed all dependencies:
```
cmake is already the newest version (3.13.4-1).
git is already the newest version (1:2.20.1-2+deb10u3).
clang is already the newest version (1:7.0-47).
libc++-dev is already the newest version (1:7.0-47).
libc++abi-dev is already the newest version (1:7.0-47).
libssl-dev is already the newest version (1.1.1d-0+deb10u3).
openssl is already the newest version (1.1.1d-0+deb10u3).
pkg-config is already the newest version (0.29-6).
libprotobuf-dev is already the newest version (3.6.1.3-2).
protobuf-compiler is already the newest version (3.6.1.3-2).
libsqlite3-dev is already the newest version (3.27.2-3).
```
But when I try to build (cargo build --release) I get the following errors:

```
warning: use of deprecated item 'configuration::loader::ConfigExtractor': Please use ConfigPath and ConfigLoader traits instead
  --> common/src/lib.rs:83:14
   |
83 |     loader::{ConfigExtractor, ConfigLoader, ConfigPath, ConfigurationError, DefaultConfigLoader, NetworkConfigPath},
   |              ^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: 1 warning emitted

   Compiling croaring-sys v0.3.9
warning: use of deprecated item 'project': consider naming projected type by passing `project` argument to #[pin_project] attribute instead, see release note <https://github.com/taiki-e/pin-project/releases/tag/v0.4.21> for details
  --> comms/dht/src/tower_filter/future.rs:59:7
   |
59 |     #[project]
   |       ^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: 1 warning emitted

error: failed to run custom build command for `croaring-sys v0.3.9`

Caused by:
  process didn't exit successfully: `/home/cluster/tari/target/release/build/croaring-sys-1b13635ef86007e0/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,mmx,sse,sse2")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = Some("fxsr,mmx,sse,sse2")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = Some("fxsr,mmx,sse,sse2")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = Some("fxsr,mmx,sse,sse2")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-std=c11" "-march=native" "-O3" "-o" "/home/cluster/tari/target/release/build/croaring-sys-4e2cb0c6f22d1220/out/CRoaring/roaring.o" "-c" "CRoaring/roaring.c"
exit code: 0
AR_x86_64-unknown-linux-gnu = None
AR_x86_64_unknown_linux_gnu = None
HOST_AR = None
AR = None
running: "ar" "crs" "/home/cluster/tari/target/release/build/croaring-sys-4e2cb0c6f22d1220/out/libroaring.a" "/home/cluster/tari/target/release/build/croaring-sys-4e2cb0c6f22d1220/out/CRoaring/roaring.o"
exit code: 0
cargo:rustc-link-lib=static=roaring
cargo:rustc-link-search=native=/home/cluster/tari/target/release/build/croaring-sys-4e2cb0c6f22d1220/out

--- stderr
/usr/include/clang/7.0.1/include/avxintrin.h:4787:10: error: invalid conversion between vector type '__m256' (vector of 8 'float' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avxintrin.h:4815:10: error: invalid conversion between vector type '__m256d' (vector of 4 'double' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avxintrin.h:4840:10: error: invalid conversion between vector type '__m256i' (vector of 4 'long long' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avxintrin.h:4869:12: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avxintrin.h:4898:12: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avxintrin.h:4927:12: error: invalid conversion between vector type '__m128i' (vector of 2 'long long' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avx512fintrin.h:965:10: error: invalid conversion between vector type '__m512d' (vector of 8 'double' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avx512fintrin.h:1002:10: error: invalid conversion between vector type '__m512' (vector of 16 'float' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avx512fintrin.h:1098:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avx512fintrin.h:1120:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avx512fintrin.h:1142:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avx512fintrin.h:1164:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avx512fintrin.h:1200:10: error: invalid conversion between vector type '__m512d' (vector of 8 'double' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avx512fintrin.h:1237:10: error: invalid conversion between vector type '__m512' (vector of 16 'float' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avx512fintrin.h:1333:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avx512fintrin.h:1355:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avx512fintrin.h:1377:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avx512fintrin.h:1399:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/7.0.1/include/avx512fintrin.h:1512:10: error: invalid conversion between vector type '__m512d' (vector of 8 'double' values) and integer type 'int' of different size
fatal error: too many errors emitted, stopping now [-ferror-limit=]
/usr/include/clang/7.0.1/include/avxintrin.h:4787:10: error: invalid conversion between vector type '__m256' (vector of 8 'float' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avxintrin.h:4815:10: error: invalid conversion between vector type '__m256d' (vector of 4 'double' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avxintrin.h:4840:10: error: invalid conversion between vector type '__m256i' (vector of 4 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avxintrin.h:4869:12: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avxintrin.h:4898:12: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avxintrin.h:4927:12: error: invalid conversion between vector type '__m128i' (vector of 2 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avx512fintrin.h:965:10: error: invalid conversion between vector type '__m512d' (vector of 8 'double' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avx512fintrin.h:1002:10: error: invalid conversion between vector type '__m512' (vector of 16 'float' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avx512fintrin.h:1098:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avx512fintrin.h:1120:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avx512fintrin.h:1142:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avx512fintrin.h:1164:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avx512fintrin.h:1200:10: error: invalid conversion between vector type '__m512d' (vector of 8 'double' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avx512fintrin.h:1237:10: error: invalid conversion between vector type '__m512' (vector of 16 'float' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avx512fintrin.h:1333:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avx512fintrin.h:1355:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avx512fintrin.h:1377:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avx512fintrin.h:1399:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/7.0.1/include/avx512fintrin.h:1512:10: error: invalid conversion between vector type '__m512d' (vector of 8 'double' values) and integer type 'int' of different size, err: true
fatal error: too many errors emitted, stopping now [-ferror-limit=], err: true
thread 'main' panicked at 'Unable to generate bindings: ()', /home/cluster/.cargo/registry/src/github.com-1ecc6299db9ec823/croaring-sys-0.3.9/build.rs:15:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Any ideas?

Thanks!

**Comment by leet4tari** [comment]
@fernandodrf , I have not yet seen this error, might be a change in default behavior for gcc on Debian 10 (buster), I have compiled from source on Ubuntu 18.04 in a VM that supports AVX and above.  
  
Mind trying with another branch that we have disabled native builds for croaring-sys? https://github.com/tari-project/tari/tree/croaring-remove-march-native  
  
Seen reports of updating llvm and clang, but I will have bring up a Debian 10 VM and test myself.

**Comment by CjS77** [comment]
Please try again with latest development HEAD. This should be resolved now. If you still get this error, set the ROARING_ARCH envar to `x86-64`, i.e.

```
$ export ROARING_ARCH="x86-64"
$ cargo build --bin tari_base_node --release
```

**Comment by fernandodrf** [comment]
Yes, it is building now, great!

**Comment by CjS77** [comment]
Awesomesauce

**Comment by mmacedoeu** [comment]
> Please try again with latest development HEAD. This should be resolved now. If you still get this error, set the ROARING_ARCH envar to `x86-64`, i.e.
> 
> ```
> $ export ROARING_ARCH="x86-64"
> $ cargo build --bin tari_base_node --release
> ```

Got the same error today with ROARING_ARCH="x86-64" but on Ubuntu 18.04

```
--- stderr
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/emmintrin.h:3427:10: error: returning 'int' from a function with incompatible result type '__m128' (vector of 4 'float' values)
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avxintrin.h:2228:10: error: invalid conversion between vector type '__m256' (vector of 8 'float' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avxintrin.h:3115:10: error: invalid conversion between vector type '__m256d' (vector of 4 'double' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avxintrin.h:3133:10: error: invalid conversion between vector type '__m256' (vector of 8 'float' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:971:10: error: invalid conversion between vector type '__m512d' (vector of 8 'double' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:982:10: error: invalid conversion between vector type '__m512d' (vector of 8 'double' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:992:10: error: invalid conversion between vector type '__m512d' (vector of 8 'double' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1021:10: error: invalid conversion between vector type '__m512' (vector of 16 'float' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1032:10: error: invalid conversion between vector type '__m512' (vector of 16 'float' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1042:10: error: invalid conversion between vector type '__m512' (vector of 16 'float' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1126:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1136:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1144:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1154:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1164:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1172:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1182:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1192:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1200:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
fatal error: too many errors emitted, stopping now [-ferror-limit=]
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/emmintrin.h:3427:10: error: returning 'int' from a function with incompatible result type '__m128' (vector of 4 'float' values), err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avxintrin.h:2228:10: error: invalid conversion between vector type '__m256' (vector of 8 'float' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avxintrin.h:3115:10: error: invalid conversion between vector type '__m256d' (vector of 4 'double' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avxintrin.h:3133:10: error: invalid conversion between vector type '__m256' (vector of 8 'float' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:971:10: error: invalid conversion between vector type '__m512d' (vector of 8 'double' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:982:10: error: invalid conversion between vector type '__m512d' (vector of 8 'double' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:992:10: error: invalid conversion between vector type '__m512d' (vector of 8 'double' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1021:10: error: invalid conversion between vector type '__m512' (vector of 16 'float' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1032:10: error: invalid conversion between vector type '__m512' (vector of 16 'float' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1042:10: error: invalid conversion between vector type '__m512' (vector of 16 'float' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1126:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1136:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1144:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1154:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1164:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1172:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1182:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1192:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/avx512fintrin.h:1200:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
fatal error: too many errors emitted, stopping now [-ferror-limit=], err: true
thread 'main' panicked at 'Unable to generate bindings: ()', /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/croaring-sys-0.4.5/build.rs:19:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by delta1** [comment]
@mmacedoeu maybe this helps? 

https://github.com/saulius/croaring-rs/issues/34#issuecomment-419623788

**Comment by mmacedoeu** [comment]
> @mmacedoeu maybe this helps?
> 
> [saulius/croaring-rs#34 (comment)](https://github.com/saulius/croaring-rs/issues/34#issuecomment-419623788)

After that I got this:

`error: linker `/usr/bin/clang` not found`

Maybe the problem is which clang version it works

**Comment by mmacedoeu** [comment]
Got it to work, maybe I missed the mininum clang version is 8
